WORKSPACE_DIR ?= $(PWD)
BSP_DIR = $(WORKSPACE_DIR)/bsp
APP_DIR = $(WORKSPACE_DIR)/app
APP_DIR_GEN = $(APP_DIR)/gen
BUILD_DIR = $(WORKSPACE_DIR)/build
BUILD_SRC_DIR = $(BUILD_DIR)/src
BUILD_STAGE_1 = ${BUILD_SRC_DIR}/stage1
BUILD_STAGE_2 = ${BUILD_SRC_DIR}/stage2